### ISSUE TITLE
Quoted ':' and '=' not backslash escaped in regexes

### ISSUE THREAD

**Issue by bpj** [ingydotnet/pegex-pm#83]
Please consider the MWE below and the regexes which get compiled from it:

``````pegex
stuff: bang | colon | equal | bang_atom | colon_atom | equal_atom

bang:  / ( '!' ) /

colon: / ( ':' ) /

equal: / ( '=' ) /

bang_atom: / ( BANG ) /

colon_atom: / ( COLON ) /

equal_atom: / ( EQUAL ) /

``````

``````yaml
---
+toprule: stuff
bang:
  .rgx: (\!)
bang_atom:
  .rgx: (!)
colon:
  .rgx: (?:)
colon_atom:
  .rgx: (:)
equal:
  .rgx: (?=)
equal_atom:
  .rgx: (=)
stuff:
  .any:
  - .ref: bang
  - .ref: colon
  - .ref: equal
  - .ref: bang_atom
  - .ref: colon_atom
  - .ref: equal_atom
``````

I know one is supposed to use the atoms but I would expect the quoted versions
to compile to something equivalent. Instead `colon` and `equal` compile to
(the useless) `(?:)` and `(?=)`. I suspect a bug here not only because I
would have expected `(\:)` and `(\=)` as results, but also because `bang`
isn't treated analogously which I would expect if it were intentional. If it is
intentional I would appreciate to learn why. If the reason is merely that one
should use the atoms I would rather like the parsing to fail on such input.

I *think* the reason for the difference is that colon and equal are among the
exceptions [here][] and [here][there], but I can vividly imagine that something
else would break if these were changed.

[here]: https://github.com/pegex-parser/pegex-pm/blob/959708ad03bbab4aace877b42c870d17e745b8cd/lib/Pegex/Bootstrap.pm#L300

[there]: https://github.com/pegex-parser/pegex-pm/blob/959708ad03bbab4aace877b42c870d17e745b8cd/lib/Pegex/Pegex/AST.pm#L121
